### ISSUE TITLE
Extension blocks all incoming sound/conversation

### ISSUE THREAD

**Issue by seahindeniz** [burkybang/Google-Meet-Auto-Disable-Mic-Cam#7]
Some time ago, I noticed that Google Meet was not sounding other peoples voices. More specifically, when I test audio from the meet settings, the dummy song is getting played and I can hear the music. When someone speaks in the meet, I can see their avatar is getting blue highlight and blue pulse animation, but I can't hear peoples voices.
When I disabled this extension, I could hear peoples voices again with no trouble.

I'm not sure if it's related to macOS update but, I have upgrade from Ventura to Sonoma and it might have an effect

**Comment by burkybang** [comment]
I have no idea how this would be possible. Is this still an issue?

**Comment by seahindeniz** [comment]
Well, I have disabled it of course but I can re-activate and observe it

**Comment by burkybang** [comment]
That would be great. I'm actively using the extension, and I have not experienced that issue.

**Comment by seahindeniz** [comment]
Just tried joining a meet and seems like the issue still persist 😞

**Comment by burkybang** [comment]
I finally experienced the issue. Refreshing the page and rejoining the meeting always resolves it though. I'm still wondering if it's unrelated to my extension. I don't see how my extension could interfere with that. For me it only happens sometimes, and I don't need to disable or uninstall the extension to resolve it, so it's difficult to know what's actually causing the issue.

**Comment by seahindeniz** [comment]
I see. Well, I have tried refreshing, reopening the page even in a new tab didn't worked. So the last resort was to disable it.

I'll try to debug it on my end, and see if I can find the root cause

**Comment by seahindeniz** [comment]
I'm not sure, but when I added a timeout timer here, the issue is no longer persists. Maybe Chrome's framework is getting triggered before it's getting ready state. I'm not talking about the DOM-ready, but it can be a framework issue.
Having a little delay seems to sort this issue out, however, I'll be observing it for the next days

![image](https://github.com/burkybang/Google-Meet-Auto-Disable-Mic-Cam/assets/5789670/868933e0-e1b7-4357-ba73-fdbcd5a2f4f6)

**Comment by burkybang** [comment]
Nice! I'll give that a try too.

**Comment by burkybang** [comment]
@seahindeniz How has it been with the delay?

**Comment by seahindeniz** [comment]
So far no trouble at all. Works like a charm

**Comment by burkybang** [comment]
Alright cool, I'll push a new update with the delay

**Comment by burkybang** [comment]
I made some other changes. Would you mind pulling them and testing before I push the next update to everyone?

**Comment by burkybang** [comment]
I pushed them to everyone.

**Comment by seahindeniz** [comment]
Sorry for delaying, I was dealing with a time taking personal matter. I can pull and test it if you still need it

**Comment by burkybang** [comment]
No worries! I was feeling confident it would work this time, so I decided to go for it. Yeah, that would be helpful. You can pull from the repo or use the one in the store. They are the same now.

**Comment by seahindeniz** [comment]
I just joined to a meeting and the sound issue is still there 😔

**Comment by burkybang** [comment]
So you chose to use the one on the store? Did it get updated to version 3.1.0 for you? If not, then it would definitely have the same issue.

**Comment by seahindeniz** [comment]
Yeah, I currently have 3.0.0 the local version and 3.1.0 the store version. Enabling store version blocks audio completely. If I switch back to local version 3.0.0, working fine. However, when I enable it the first time yesterday, the local version was also interrupted audio too but when I rejoin the meeting again, issue got solved. I think it must be insufficient countdown that I added for 500ms

**Comment by burkybang** [comment]
I added more of a delay into the repo version. Can you test again please?
